[General]
DisplayServer=wayland
Numlock=on

[Theme]
Current=Sugar-Candy
CursorTheme=Ado-Cursor

[Wayland]
CompositorCommand=/usr/bin/kwin_wayland --no-lockscreen
SessionDir=/usr/share/wayland-sessions
EnableHiDPI=true
