#! /usr/bin/env bash

HYPRCONF_DIR="$HOME/.config/hypr"

printf "${TEXT_CYAN}➡ Applying Hyprland configuration...${TEXT_RST}\n"

cp "$SCRIPT_DIR/configs/hyprland/monitors.lua" "$HYPRCONF_DIR"
cp "$SCRIPT_DIR/configs/hyprland/workspaces.lua" "$HYPRCONF_DIR"
cp -r "$SCRIPT_DIR/configs/hyprland/custom" "$HYPRCONF_DIR"

hyprctl reload

printf "${TEXT_GREEN}✓ Hyprland configuration applied${TEXT_RST}\n"