#! /usr/bin/env bash

HYPRCONF_DIR="$HOME/.config/hypr"

printf "${TEXT_CYAN}➡ Applying Hyprland configuration...${TEXT_RST}\n"

cp "../configs/hyprland/monitors.conf" "$HYPRCONF_DIR"
cp "../configs/hyprland/workspaces.conf" "$HYPRCONF_DIR"
cp -r "../configs/hyprland/custom" "$HYPRCONF_DIR"

hyprctl reload

printf "${TEXT_GREEN}✓ Hyprland configuration applied${TEXT_RST}\n"